name: deploy

on:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Set up Python
        run: uv python install
      - name: Install
        run: uv sync --all-extras --dev
      - name: Convert
        run: |
          uv run panel convert index.py --to pyodide-worker --out build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
